version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.9
    command: [--auth]
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zul
      - MONGO_INITDB_ROOT_PASSWORD=zul
  redis:
    container_name: redis
    image: redis:7.0.0
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
